-- Catálogo administrable del Laboratorio Virtual de Higiene Ocupacional.
-- Reutiliza Supabase Auth y el mismo permiso de gestion.movidasst.com.

begin;

create table if not exists public.laboratorio_simuladores (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nombre text not null check (char_length(nombre) between 2 and 100),
  descripcion text not null check (char_length(descripcion) between 10 and 500),
  url text,
  factor text not null check (char_length(factor) between 2 and 80),
  medicion text,
  icono text not null default 'instrumento'
    check (icono in ('instrumento', 'sonometro', 'luxometro', 'gases', 'anemometro', 'wbgt')),
  etiquetas text[] not null default '{}',
  estado text not null default 'Próximamente'
    check (estado in ('Disponible', 'Beta', 'Nueva', 'En desarrollo', 'Próximamente')),
  destacada boolean not null default false,
  publicada boolean not null default false,
  archivada boolean not null default false,
  orden integer not null default 100 check (orden between 0 and 10000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint laboratorio_simuladores_url_https
    check (url is null or url ~ '^https://[^[:space:]]+$')
);

alter table public.laboratorio_simuladores enable row level security;

revoke all on table public.laboratorio_simuladores from anon, authenticated;
revoke all on sequence public.laboratorio_simuladores_id_seq from anon, authenticated;
grant select on table public.laboratorio_simuladores to anon, authenticated;

drop policy if exists laboratorio_publico_lectura on public.laboratorio_simuladores;
create policy laboratorio_publico_lectura
on public.laboratorio_simuladores
for select
to anon, authenticated
using (publicada = true and archivada = false);

create or replace function public.laboratorio_simuladores_publicos()
returns table (
  id bigint,
  slug text,
  nombre text,
  descripcion text,
  url text,
  factor text,
  medicion text,
  icono text,
  etiquetas text[],
  estado text,
  destacada boolean,
  publicada boolean,
  archivada boolean,
  orden integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    s.id, s.slug, s.nombre, s.descripcion, s.url, s.factor, s.medicion,
    s.icono, s.etiquetas, s.estado, s.destacada, s.publicada, s.archivada, s.orden
  from public.laboratorio_simuladores s
  where s.publicada = true and s.archivada = false
  order by s.destacada desc, s.orden asc, s.nombre asc;
$$;

create or replace function public.laboratorio_admin_listar()
returns table (
  id bigint,
  slug text,
  nombre text,
  descripcion text,
  url text,
  factor text,
  medicion text,
  icono text,
  etiquetas text[],
  estado text,
  destacada boolean,
  publicada boolean,
  archivada boolean,
  orden integer,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.es_admin_gestion() then
    raise exception 'No autorizado';
  end if;

  return query
  select
    s.id, s.slug, s.nombre, s.descripcion, s.url, s.factor, s.medicion,
    s.icono, s.etiquetas, s.estado, s.destacada, s.publicada, s.archivada,
    s.orden, s.created_at, s.updated_at
  from public.laboratorio_simuladores s
  order by s.archivada asc, s.orden asc, s.nombre asc;
end;
$$;

create or replace function public.laboratorio_admin_guardar(p_datos jsonb)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_nombre text;
  v_descripcion text;
  v_factor text;
  v_medicion text;
  v_url text;
  v_estado text;
  v_icono text;
  v_etiquetas text[];
  v_orden integer;
  v_publicada boolean;
  v_destacada boolean;
  v_slug text;
  v_slug_base text;
  v_suffix integer := 1;
begin
  if not private.es_admin_gestion() then
    raise exception 'No autorizado';
  end if;

  if p_datos is null or jsonb_typeof(p_datos) <> 'object' then
    raise exception 'Los datos del simulador no son válidos';
  end if;

  if exists (
    select 1
    from jsonb_object_keys(p_datos) as k(key)
    where k.key not in (
      'id', 'nombre', 'descripcion', 'url', 'factor', 'medicion', 'icono',
      'etiquetas', 'estado', 'destacada', 'publicada', 'orden'
    )
  ) then
    raise exception 'El formulario contiene campos no permitidos';
  end if;

  v_id := nullif(p_datos ->> 'id', '')::bigint;
  v_nombre := btrim(p_datos ->> 'nombre');
  v_descripcion := btrim(p_datos ->> 'descripcion');
  v_factor := btrim(p_datos ->> 'factor');
  v_medicion := nullif(btrim(p_datos ->> 'medicion'), '');
  v_url := nullif(btrim(p_datos ->> 'url'), '');
  v_estado := coalesce(nullif(btrim(p_datos ->> 'estado'), ''), 'Próximamente');
  v_icono := coalesce(nullif(btrim(p_datos ->> 'icono'), ''), 'instrumento');
  v_orden := greatest(0, least(10000, coalesce((p_datos ->> 'orden')::integer, 100)));
  v_publicada := coalesce((p_datos ->> 'publicada')::boolean, false);
  v_destacada := coalesce((p_datos ->> 'destacada')::boolean, false);

  if char_length(v_nombre) not between 2 and 100 then
    raise exception 'El nombre debe tener entre 2 y 100 caracteres';
  end if;
  if char_length(v_descripcion) not between 10 and 500 then
    raise exception 'La descripción debe tener entre 10 y 500 caracteres';
  end if;
  if char_length(v_factor) not between 2 and 80 then
    raise exception 'El área debe tener entre 2 y 80 caracteres';
  end if;
  if v_medicion is not null and char_length(v_medicion) > 100 then
    raise exception 'El campo de medición no puede superar 100 caracteres';
  end if;
  if v_url is not null and v_url !~ '^https://[^[:space:]]+$' then
    raise exception 'La dirección debe ser una URL segura https://';
  end if;
  if v_estado not in ('Disponible', 'Beta', 'Nueva', 'En desarrollo', 'Próximamente') then
    raise exception 'El estado seleccionado no es válido';
  end if;
  if v_icono not in ('instrumento', 'sonometro', 'luxometro', 'gases', 'anemometro', 'wbgt') then
    raise exception 'El icono seleccionado no es válido';
  end if;

  if jsonb_typeof(p_datos -> 'etiquetas') = 'array' then
    v_etiquetas := array(
      select left(btrim(tag), 60)
      from jsonb_array_elements_text(p_datos -> 'etiquetas') as item(tag)
      where nullif(btrim(tag), '') is not null
      limit 12
    );
  else
    v_etiquetas := '{}';
  end if;

  if v_id is null then
    v_slug_base := trim(both '-' from regexp_replace(
      lower(translate(v_nombre, 'áéíóúüñÁÉÍÓÚÜÑ', 'aeiouunAEIOUUN')),
      '[^a-z0-9]+', '-', 'g'
    ));
    if v_slug_base = '' then
      v_slug_base := 'simulador';
    end if;
    v_slug := v_slug_base;
    while exists (select 1 from public.laboratorio_simuladores s where s.slug = v_slug) loop
      v_suffix := v_suffix + 1;
      v_slug := v_slug_base || '-' || v_suffix::text;
    end loop;

    insert into public.laboratorio_simuladores (
      slug, nombre, descripcion, url, factor, medicion, icono, etiquetas,
      estado, destacada, publicada, orden
    ) values (
      v_slug, v_nombre, v_descripcion, v_url, v_factor, v_medicion, v_icono,
      v_etiquetas, v_estado, v_destacada, v_publicada, v_orden
    ) returning id into v_id;
  else
    update public.laboratorio_simuladores s
    set nombre = v_nombre,
        descripcion = v_descripcion,
        url = v_url,
        factor = v_factor,
        medicion = v_medicion,
        icono = v_icono,
        etiquetas = v_etiquetas,
        estado = v_estado,
        destacada = v_destacada,
        publicada = v_publicada,
        orden = v_orden,
        updated_at = now()
    where s.id = v_id;

    if not found then
      raise exception 'El simulador no existe';
    end if;
  end if;

  return v_id;
end;
$$;

create or replace function public.laboratorio_admin_publicar(p_id bigint, p_publicada boolean)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.es_admin_gestion() then
    raise exception 'No autorizado';
  end if;

  update public.laboratorio_simuladores
  set publicada = coalesce(p_publicada, false), updated_at = now()
  where id = p_id;

  if not found then
    raise exception 'El simulador no existe';
  end if;
  return true;
end;
$$;

create or replace function public.laboratorio_admin_archivar(p_id bigint, p_archivar boolean)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.es_admin_gestion() then
    raise exception 'No autorizado';
  end if;

  update public.laboratorio_simuladores
  set archivada = coalesce(p_archivar, true), updated_at = now()
  where id = p_id;

  if not found then
    raise exception 'El simulador no existe';
  end if;
  return true;
end;
$$;

revoke all on function public.laboratorio_simuladores_publicos() from public;
revoke all on function public.laboratorio_admin_listar() from public;
revoke all on function public.laboratorio_admin_guardar(jsonb) from public;
revoke all on function public.laboratorio_admin_publicar(bigint, boolean) from public;
revoke all on function public.laboratorio_admin_archivar(bigint, boolean) from public;
revoke all on function public.laboratorio_admin_listar() from anon;
revoke all on function public.laboratorio_admin_guardar(jsonb) from anon;
revoke all on function public.laboratorio_admin_publicar(bigint, boolean) from anon;
revoke all on function public.laboratorio_admin_archivar(bigint, boolean) from anon;

grant execute on function public.laboratorio_simuladores_publicos() to anon, authenticated;
grant execute on function public.laboratorio_admin_listar() to authenticated;
grant execute on function public.laboratorio_admin_guardar(jsonb) to authenticated;
grant execute on function public.laboratorio_admin_publicar(bigint, boolean) to authenticated;
grant execute on function public.laboratorio_admin_archivar(bigint, boolean) to authenticated;

insert into public.laboratorio_simuladores (
  slug, nombre, descripcion, url, factor, medicion, icono, etiquetas,
  estado, destacada, publicada, orden
) values
  (
    'sonometro-virtual', 'Sonómetro virtual',
    'Practica ponderaciones A, C y Z, respuesta temporal, rangos, Leq, máximos y análisis por bandas de octava y tercio de octava.',
    'https://sonometro.movidasst.com', 'Ruido ocupacional', 'Nivel de presión sonora · dB',
    'sonometro', array['Leq', 'dB(A)', 'Octavas', '1/3 de octava'],
    'Disponible', true, true, 10
  ),
  (
    'luxometro-virtual', 'Luxómetro virtual',
    'Aprende a seleccionar el rango, ubicar el sensor y comprender la iluminancia antes de realizar una evaluación en puestos de trabajo.',
    'https://luxometro.movidasst.com', 'Iluminación', 'Iluminancia · lux',
    'luxometro', array['Iluminancia', 'Rango', 'Plano de trabajo'],
    'En desarrollo', false, true, 20
  ),
  (
    'detector-multigas', 'Detector multigás',
    'Reconoce sensores, alarmas, comprobación funcional y lectura simultánea de gases en atmósferas potencialmente peligrosas.',
    null, 'Agentes químicos', 'Concentración · ppm, %LEL y %vol',
    'gases', array['O₂', 'CO', 'H₂S', 'LEL'],
    'Próximamente', false, true, 30
  ),
  (
    'anemometro-virtual', 'Anemómetro virtual',
    'Practica la medición de velocidad del aire y el recorrido de puntos para evaluar ventilación y corrientes en el ambiente laboral.',
    null, 'Ventilación', 'Velocidad del aire · m/s',
    'anemometro', array['Ventilación', 'Caudal', 'Velocidad'],
    'Próximamente', false, true, 40
  ),
  (
    'medidor-tgbh-wbgt', 'Medidor de estrés térmico TGBH / WBGT',
    'Comprende las temperaturas de globo, bulbo húmedo natural y bulbo seco que se combinan para estimar el estrés térmico.',
    null, 'Estrés térmico', 'Índice TGBH / WBGT · °C',
    'wbgt', array['TGBH', 'WBGT', 'Carga térmica'],
    'Próximamente', false, true, 50
  )
on conflict (slug) do nothing;

commit;
