(() => {
'use strict';
const $=id=>document.getElementById(id), $$=sel=>[...document.querySelectorAll(sel)], clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const scenarios={
 office:{label:'Oficina con aire acondicionado',base:.16,temp:22.5,turb:.18,flow:'variable'},
 diffuser:{label:'Puesto bajo difusor',base:.42,temp:20.5,turb:.30,flow:'down'},
 window:{label:'Puesto junto a ventana',base:.55,temp:23.2,turb:.42,flow:'side'},
 industrial:{label:'Área industrial variable',base:1.35,temp:29.0,turb:.28,flow:'variable'},
 grille:{label:'Salida de ventilación',base:3.8,temp:18.8,turb:.12,flow:'direct'},
 duct:{label:'Ducto de ventilación',base:7.2,temp:19.5,turb:.10,flow:'direct'}
};
const modes={
 hotwire:{title:'HOT WIRE · Hilo caliente',badge:'0–20 m/s · 0,01 m/s',range:[0,20],resolution:.01,warmup:5,dirFactor:{0:1,30:.92,60:.62,90:.18}},
 vane:{title:'VANE · Hélice',badge:'0,4–20 m/s · 0,1 m/s',range:[.4,20],resolution:.1,warmup:0,dirFactor:{0:1,30:.87,60:.52,90:.10}},
 pitot:{title:'PITOT · Ducto avanzado',badge:'Δp → velocidad local',range:[0,60],resolution:.01,warmup:0,dirFactor:{0:1,30:.75,60:.25,90:.03}}
};
const heightFactors={seated:{head:1.08,abdomen:1.00,ankles:1.22},standing:{head:1.04,abdomen:1.00,ankles:1.18}};
const heightLabels={seated:{head:'Cabeza · 1,1 m',abdomen:'Abdomen · 0,6 m',ankles:'Tobillos · 0,1 m'},standing:{head:'Cabeza · 1,7 m',abdomen:'Abdomen · 1,1 m',ankles:'Tobillos · 0,1 m'}};
const unitFns={ms:{label:'m/s',factor:1},fpm:{label:'fpm',factor:196.8504},kmh:{label:'km/h',factor:3.6}};
const state={mode:'hotwire',scenario:'office',posture:'seated',height:'abdomen',orientation:0,unit:'ms',powered:false,warmed:false,warming:false,running:false,hold:false,displayMode:'live',samples:[],current:null,min:null,max:null,avg:null,sd:null,tu:null,temp:22.5,startAt:0,elapsed:0,trend:[],heights:{},points:[],pitot:[],mem:loadMemory()};
let timer=null,warmTimer=null,toastTimer=null;
function loadMemory(){try{return JSON.parse(localStorage.getItem('movida-anemometro-memory')||'[]')}catch{return []}}
function saveMemory(){localStorage.setItem('movida-anemometro-memory',JSON.stringify(state.mem.slice(0,20)))}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300)}
function fmtTime(s){s=Math.floor(s);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function unit(){return unitFns[state.unit]}
function conv(v){return Number.isFinite(v)?v*unit().factor:null}
function fmt(v){if(!Number.isFinite(v))return '----';const x=conv(v),res=modes[state.mode].resolution*unit().factor;return res<.1?x.toFixed(2):res<1?x.toFixed(1):Math.round(x).toLocaleString('es-ES')}
function calcStats(){const a=state.samples;if(!a.length){state.avg=state.sd=state.tu=null;return}state.avg=a.reduce((x,y)=>x+y,0)/a.length;state.sd=a.length>1?Math.sqrt(a.reduce((s,v)=>s+(v-state.avg)**2,0)/(a.length-1)):0;state.tu=state.avg>0?state.sd/state.avg*100:0}
function spatialFactor(){return heightFactors[state.posture][state.height]||1}
function simulatedVelocity(){const s=scenarios[state.scenario],m=modes[state.mode],t=performance.now()/1000;const dir=m.dirFactor[state.orientation]??1;let base=s.base*spatialFactor();if(state.mode==='vane'&&base<.4) base*=.78;const wave=Math.sin(t*2.1)*s.turb*base*.65+Math.sin(t*.63+1.2)*s.turb*base*.35;const random=(Math.random()-.5)*s.turb*base*.7;return Math.max(0,(base+wave+random)*dir)}
function updateHeightOptions(){const lab=heightLabels[state.posture];$('heightSelect').innerHTML=Object.entries(lab).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');if(!lab[state.height])state.height='abdomen';$('heightSelect').value=state.height;renderHeightResults()}
function updateModeUI(){const m=modes[state.mode];$('modeTitle').textContent=m.title;$('probeBadge').textContent=m.badge;$('screenMode').textContent=state.mode==='hotwire'?'HOT':state.mode==='vane'?'VANE':'PIT';$('probeVisual').className=`probe ${state.mode}`;$('pitotBox').hidden=state.mode!=='pitot';$('flowAreaBox').hidden=state.mode==='pitot';$$('.mode-card').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));if(state.mode==='pitot')switchTab('pitot');updateQuality();updateLesson()}
function power(){if(state.powered){stop();state.powered=false;state.warmed=false;state.warming=false;clearTimeout(warmTimer);update();return}state.powered=true;state.warmed=modes[state.mode].warmup===0;if(!state.warmed){state.warming=true;warmTimer=setTimeout(()=>{state.warming=false;state.warmed=true;toast('Sensor térmico listo');update()},1800)}toast(state.warmed?'Equipo encendido':'Calentando sensor térmico…');update()}
function startStop(){if(!state.powered)return toast('Enciende primero el equipo');if(state.running){stop();toast('Medición detenida');return update()}if(!state.warmed)return toast('Espera el calentamiento de la sonda');state.running=true;state.hold=false;state.samples=[];state.trend=[];state.startAt=performance.now();state.elapsed=0;sample();timer=setInterval(sample,500);update()}
function stop(){clearInterval(timer);timer=null;state.running=false;state.hold=false}
function sample(){if(!state.running||state.hold)return;const v=simulatedVelocity();state.current=v;state.samples.push(v);if(state.samples.length>600)state.samples.shift();state.min=state.min==null?v:Math.min(state.min,v);state.max=state.max==null?v:Math.max(state.max,v);state.temp=scenarios[state.scenario].temp+(Math.random()-.5)*.15;state.elapsed=(performance.now()-state.startAt)/1000;calcStats();state.trend.push(v);if(state.trend.length>80)state.trend.shift();update(false)}
function currentForDisplay(){if(state.displayMode==='max')return state.max;if(state.displayMode==='min')return state.min;if(state.displayMode==='avg')return state.avg;return state.current}
function toggleHold(){if(!state.running)return toast('Inicia una medición');state.hold=!state.hold;update()}
function cycleDisplay(){const a=['live','max','min','avg'];state.displayMode=a[(a.indexOf(state.displayMode)+1)%a.length];update()}
function avgMode(){state.displayMode='avg';update();toast('Mostrando promedio temporal')}
function cycleUnit(){const a=['ms','fpm','kmh'];state.unit=a[(a.indexOf(state.unit)+1)%a.length];$('unitSelect').value=state.unit;update()}
function flowRate(){if(!Number.isFinite(state.avg)||state.mode==='pitot')return null;const A=Math.max(.0001,(Number($('areaWidth').value)||0)*(Number($('areaHeight').value)||0));return state.avg*A*3600}
function update(full=true){const val=currentForDisplay();$('screen').classList.toggle('off',!state.powered);$('screenStatus').textContent=!state.powered?'OFF':state.warming?'WARM':state.hold?'HOLD':state.running?state.displayMode.toUpperCase():'READY';$('mainReading').textContent=fmt(val);$('mainUnit').textContent=unit().label;$('avgReading').textContent=fmt(state.avg);$('maxReading').textContent=fmt(state.max);$('minReading').textContent=fmt(state.min);$('sdReading').textContent=fmt(state.sd);$('tuReading').textContent=Number.isFinite(state.tu)?`${state.tu.toFixed(1)}%`:'----';$('tempReading').textContent=`${state.temp.toFixed(1)} °C`;$('timerReading').textContent=fmtTime(state.elapsed);$('sampleCount').textContent=state.samples.length;$('flowReading').textContent=Number.isFinite(flowRate())?`${Math.round(flowRate()).toLocaleString('es-ES')} m³/h`:'----';$('runBtn').classList.toggle('active',state.running);$('mobileRun').classList.toggle('active',state.running);$('mobileRun').querySelector('span').textContent=state.running?'Parar':'Medir';$('qualityState').textContent=qualitySummary();updateQuality();updateLesson();updateGuide();renderTrend();if(full)renderHeightResults()}
function qualitySummary(){const flags=qualityFlags();const bad=flags.filter(f=>!f.ok).length;return bad===0?'Correcta':bad<=2?'Revisar':'Deficiente'}
function qualityFlags(){const flags=[];flags.push({ok:state.powered,text:state.powered?'Equipo encendido':'Equipo apagado'});if(state.mode==='hotwire')flags.push({ok:state.warmed,text:state.warmed?'Sensor calentado':'Sensor aún no listo'});flags.push({ok:state.orientation===0,text:state.orientation===0?'Sonda alineada con el flujo':`Orientación ${state.orientation}°: posible sesgo`});if(state.mode==='vane')flags.push({ok:(state.current??scenarios[state.scenario].base)>=.4,text:(state.current??scenarios[state.scenario].base)>=.4?'Dentro del rango útil de hélice':'Velocidad muy baja para este modo VANE'});flags.push({ok:state.samples.length>=10,text:state.samples.length>=10?'Período con varias muestras':'Aún hay pocas muestras'});flags.push({ok:state.samples.length===0||Number.isFinite(state.avg),text:'Promedio temporal disponible'});return flags}
function updateQuality(){$('qualityFlags').innerHTML=qualityFlags().map(f=>`<div class="flag ${f.ok?'ok':'warn'}"><b>${f.ok?'✓':'!'}</b><span>${f.text}</span></div>`).join('')}
function updateLesson(){let k='SELECCIÓN DE SONDA',t='No todos los anemómetros sirven igual',p='HOT WIRE es el modo preferido para bajas velocidades; VANE para corrientes definidas; PITOT para ductos.';if(state.powered&&!state.warmed){k='CALENTAMIENTO';t='La sonda térmica necesita estabilizarse';p='El manual del Testo 425 indica un calentamiento inicial del sensor. En el simulador se comprime a unos segundos.'}else if(state.orientation!==0){k='ORIENTACIÓN';t='Busca la dirección principal del flujo';p='Una sonda direccional mal orientada subestima la velocidad. Corrige el ángulo antes de registrar.'}else if(state.running&&state.samples.length<10){k='TIEMPO DE MEDICIÓN';t='No interpretes una lectura instantánea';p='Deja acumular muestras. La velocidad del aire fluctúa y la media depende del período de medición.'}else if(state.running&&Number.isFinite(state.tu)){k='TURBULENCIA';t='Promedio y fluctuación cuentan historias distintas';p=`La media es ${state.avg.toFixed(2)} m/s y TU ${state.tu.toFixed(1)}%. Un mismo promedio puede coexistir con distinta variabilidad.`}else if(Object.keys(state.heights).length){k='PERFIL VERTICAL';t='Compara cabeza, abdomen y tobillos';p='Las diferencias entre alturas ayudan a reconocer un ambiente heterogéneo alrededor del trabajador.'}$('lessonKicker').textContent=k;$('lessonTitle').textContent=t;$('lessonText').textContent=p;$('formulaResult').textContent=Number.isFinite(state.tu)?`SD ${state.sd.toFixed(3)} m/s · v̄ ${state.avg.toFixed(3)} m/s · TU ${state.tu.toFixed(1)}%`:'—'}
function recordHeight(){if(!Number.isFinite(state.avg||state.current))return toast('Realiza una medición primero');state.heights[state.height]=state.avg||state.current;renderHeightResults();toast(`${heightLabels[state.posture][state.height]} registrado`)}
function renderHeightResults(){const lab=heightLabels[state.posture];$('heightResults').innerHTML=Object.keys(lab).map(k=>`<div><span>${lab[k]}</span><b>${Number.isFinite(state.heights[k])?state.heights[k].toFixed(2)+' m/s':'—'}</b></div>`).join('')}
function addPoint(){const v=state.avg||state.current;if(!Number.isFinite(v))return toast('Realiza una medición');state.points.push(v);renderPoints();toast('Punto agregado')}
function renderPoints(){const avg=state.points.length?state.points.reduce((a,b)=>a+b,0)/state.points.length:null;$('pointList').innerHTML=(state.points.map((v,i)=>`<div><span>P${i+1}</span><b>${v.toFixed(2)} m/s</b></div>`).join('')||'<p class="note">Sin puntos registrados.</p>')+(Number.isFinite(avg)?`<div class="point-avg"><span>Promedio espacial</span><b>${avg.toFixed(2)} m/s</b></div>`:'')}
function renderTrend(){const arr=state.trend;if(!arr.length)return $('trendLine').setAttribute('points','');const max=Math.max(...arr,1),min=0;const pts=arr.map((v,i)=>`${i/(Math.max(1,arr.length-1))*900},${245-(v-min)/(max-min||1)*220}`).join(' ');$('trendLine').setAttribute('points',pts)}
function generatePitot(){if(state.mode!=='pitot'){state.mode='pitot';updateModeUI()}const shape=$('ductShape').value;const count=shape==='round'?12:25;state.pitot=Array.from({length:count},(_,i)=>({i,dp:null,v:null}));renderPitot();toast(`${count} puntos generados`)}
function ductArea(){const a=Number($('ductA').value)||.5,b=Number($('ductB').value)||.4;return $('ductShape').value==='round'?Math.PI*a*a/4:a*b}
function recordPitot(i){const rho=Number($('airDensity').value)||1.2, s=scenarios[state.scenario];const n=state.pitot.length;const pos=(i+.5)/n;const profile=.45+.65*Math.sin(Math.PI*pos);const v=s.base*profile*(.96+Math.random()*.08);const dp=.5*rho*v*v;state.pitot[i]={i,dp,v};renderPitot()}
function renderPitot(){const grid=$('pitotGrid');if(!state.pitot.length){grid.innerHTML='';$('pitotSummary').textContent='Sin recorrido generado.';return}grid.innerHTML=state.pitot.map(p=>`<button class="${Number.isFinite(p.v)?'done':''}" data-pitot="${p.i}"><span>P${p.i+1}</span><b>${Number.isFinite(p.dp)?p.dp.toFixed(1)+' Pa':'Δp'}</b><small>${Number.isFinite(p.v)?p.v.toFixed(2)+' m/s':'pendiente'}</small></button>`).join('');$$('[data-pitot]').forEach(b=>b.addEventListener('click',()=>recordPitot(Number(b.dataset.pitot))));const vals=state.pitot.map(p=>p.v).filter(Number.isFinite);if(vals.length){const avg=vals.reduce((a,b)=>a+b,0)/vals.length,q=avg*ductArea()*3600;$('pitotSummary').innerHTML=`<b>${vals.length}/${state.pitot.length} puntos</b> · v̄ ${avg.toFixed(2)} m/s · Q ${Math.round(q).toLocaleString('es-ES')} m³/h`}}
function switchTab(tab){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));['trend','multipoint','pitot','memory'].forEach(t=>$(`${t}Pane`).hidden=t!==tab)}
function savePractice(){state.mem.unshift({date:new Date().toISOString(),mode:state.mode,scenario:scenarios[state.scenario].label,avg:state.avg,sd:state.sd,tu:state.tu,samples:state.samples.length});saveMemory();renderMemory();toast('Práctica guardada')}
function renderMemory(){if(!state.mem.length){$('memoryList').innerHTML='<p class="note">Sin prácticas guardadas.</p>';return}$('memoryList').innerHTML=state.mem.map(m=>`<article><span>${new Date(m.date).toLocaleString('es-ES')}</span><b>${m.mode.toUpperCase()} · ${m.scenario}</b><small>${Number.isFinite(m.avg)?`v̄ ${m.avg.toFixed(2)} m/s · TU ${m.tu?.toFixed(1)??'—'}% · ${m.samples} muestras`:'Sin promedio'}</small></article>`).join('')}
const guide=[()=>state.mode,()=>state.powered,()=>state.mode!=='hotwire'||state.warmed,()=>state.orientation===0,()=>state.running||state.samples.length>0,()=>state.samples.length>=10,()=>Object.keys(state.heights).length>0];const titles=['Selecciona el modo','Enciende el equipo','Espera la estabilización','Alinea la sonda','Inicia la medición','Deja acumular muestras','Registra una altura'];const texts=['HOT WIRE para ambiente ocupacional; VANE para ventilación; PITOT para ductos.','Pulsa POWER.','En hilo caliente espera el calentamiento del sensor.','La orientación respecto al flujo afecta la lectura.','Pulsa START/STOP.','Observa promedio, SD y TU antes de interpretar.','Guarda cabeza, abdomen o tobillos para construir el perfil vertical.'];function guideIndex(){return guide.findIndex(fn=>!fn())}function updateGuide(){let i=guideIndex();if(i<0)i=guide.length;const pct=Math.round(i/guide.length*100);$('guidePct').textContent=`${pct}%`;$('guideBar').style.width=`${pct}%`;if(i===guide.length){$('guideStep').textContent='Práctica completada';$('guideTitle').textContent='Explora escenarios y modos';$('guideText').textContent='Compara sondas, alturas y promedios.'}else{$('guideStep').textContent=`Paso ${i+1} de ${guide.length}`;$('guideTitle').textContent=titles[i];$('guideText').textContent=texts[i]}}
function locateGuide(){const i=guideIndex();const targets=['#modeCards','#powerBtn','#screen','#orientationSelect','#runBtn','#screen','#recordHeightBtn'];const el=document.querySelector(targets[Math.max(0,i)]);el?.scrollIntoView({behavior:'smooth',block:'center'});el?.classList.add('pulse');setTimeout(()=>el?.classList.remove('pulse'),1400)}
function bind(){
 $$('.mode-card').forEach(b=>b.addEventListener('click',()=>{stop();state.mode=b.dataset.mode;state.warmed=false;state.warming=false;state.current=state.avg=state.sd=state.tu=state.min=state.max=null;state.samples=[];updateModeUI();update()}));
 $('scenarioSelect').addEventListener('change',e=>{state.scenario=e.target.value;state.temp=scenarios[state.scenario].temp;update()});$('postureSelect').addEventListener('change',e=>{state.posture=e.target.value;state.heights={};updateHeightOptions();update()});$('heightSelect').addEventListener('change',e=>{state.height=e.target.value;update()});$('orientationSelect').addEventListener('change',e=>{state.orientation=Number(e.target.value);update()});$('unitSelect').addEventListener('change',e=>{state.unit=e.target.value;update()});
 $('powerBtn').addEventListener('click',power);$('runBtn').addEventListener('click',startStop);$('mobileRun').addEventListener('click',startStop);$('holdBtn').addEventListener('click',toggleHold);$('modeBtn').addEventListener('click',cycleDisplay);$('avgBtn').addEventListener('click',avgMode);$('unitBtn').addEventListener('click',cycleUnit);$('recordHeightBtn').addEventListener('click',recordHeight);$('addPointBtn').addEventListener('click',addPoint);$('resetTrend').addEventListener('click',()=>{state.trend=[];renderTrend()});$('generatePitotBtn').addEventListener('click',generatePitot);$('savePractice').addEventListener('click',savePractice);$('clearMemory').addEventListener('click',()=>{state.mem=[];saveMemory();renderMemory()});$('guideLocate').addEventListener('click',locateGuide);$('manualBtn').addEventListener('click',()=>$('manualDialog').showModal());$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$$('[data-mobile]').forEach(b=>b.addEventListener('click',()=>{const map={setup:'.setup-panel',meter:'.instrument-panel',learn:'.learning-panel'};document.querySelector(map[b.dataset.mobile])?.scrollIntoView({behavior:'smooth',block:'start'})}));
}
function init(){updateHeightOptions();bind();renderPoints();renderMemory();renderPitot();updateModeUI();update();}
init();
})();