(() => {
'use strict';
const $=id=>document.getElementById(id);
const SUPABASE_URL='https://lfdmbkzghnwvsapxypvt.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1';
const SESSION='movida-sst-anemometro-session', ATTEMPTS='movida-sst-anemometro-attempts';
const ACCESS_DURATION=20*60*1000, BLOCK_DURATION=15*60*1000, MAX_ATTEMPTS=5;
let timer=null;
function read(storage,key,fallback){try{return JSON.parse(storage.getItem(key)||'null')||fallback}catch{return fallback}}
function write(storage,key,val){try{storage.setItem(key,JSON.stringify(val))}catch{}}
function msg(text,type='error'){const el=$('loginMessage');el.textContent=text;el.classList.toggle('success',type==='success')}
function attempts(){const s=read(localStorage,ATTEMPTS,{count:0,blockedUntil:0});if(s.blockedUntil&&s.blockedUntil<=Date.now()){localStorage.removeItem(ATTEMPTS);return {count:0,blockedUntil:0}}return s}
function blocked(until){const m=Math.max(1,Math.ceil((until-Date.now())/60000));return `Demasiados intentos. Espera ${m} ${m===1?'minuto':'minutos'} antes de volver a intentar.`}
function failed(){const a=attempts(),count=(a.count||0)+1;if(count>=MAX_ATTEMPTS){const until=Date.now()+BLOCK_DURATION;write(localStorage,ATTEMPTS,{count:0,blockedUntil:until});return blocked(until)}write(localStorage,ATTEMPTS,{count,blockedUntil:0});return `No pudimos validar esos datos. Te ${MAX_ATTEMPTS-count===1?'queda 1 intento':`quedan ${MAX_ATTEMPTS-count} intentos`}.`}
function open(member,persist=true){const name=[member?.nombres,member?.apellidos].filter(Boolean).join(' ').trim()||member?.name||'integrante';const expiresAt=member?.expiresAt||Date.now()+ACCESS_DURATION;if(persist)write(sessionStorage,SESSION,{name,expiresAt});$('memberName').textContent=name;$('loginGate').hidden=true;$('appShell').hidden=false;$('appShell').setAttribute('aria-hidden','false');document.body.classList.remove('auth-locked');clearTimeout(timer);timer=setTimeout(()=>close(true),Math.max(0,expiresAt-Date.now()))}
function close(expired=false){clearTimeout(timer);sessionStorage.removeItem(SESSION);if(expired)sessionStorage.setItem('movida-sst-anemometro-expired','1');location.reload()}
async function submit(e){e.preventDefault();const cedula=$('memberId').value.replace(/\D/g,''),codigo=$('memberPassword').value.trim(),a=attempts();if(a.blockedUntil>Date.now())return msg(blocked(a.blockedUntil));if(!cedula||!codigo)return msg('Escribe tu cédula y tu clave para continuar.');const btn=$('loginSubmit');btn.disabled=true;btn.querySelector('span').textContent='Verificando acceso…';msg('','success');try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/acceso_integrante`,{method:'POST',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${SUPABASE_PUBLISHABLE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_cedula:cedula,p_codigo:codigo})});if(!r.ok)throw new Error(`Access ${r.status}`);const p=await r.json(),member=Array.isArray(p)?p[0]:p;if(!member){$('memberPassword').value='';return msg(failed())}localStorage.removeItem(ATTEMPTS);$('memberLogin').reset();open(member)}catch(err){console.error(err);msg('El servicio de acceso no está disponible en este momento. Intenta nuevamente en unos minutos.')}finally{btn.disabled=false;btn.querySelector('span').textContent='Abrir laboratorio'}}
function init(){ $('memberLogin').addEventListener('submit',submit);$('togglePassword').addEventListener('click',()=>{const f=$('memberPassword'),show=f.type==='password';f.type=show?'text':'password';$('togglePassword').textContent=show?'Ocultar':'Mostrar'});$('logoutBtn').addEventListener('click',()=>close(false));const s=read(sessionStorage,SESSION,null);if(s?.expiresAt>Date.now())return open(s,false);sessionStorage.removeItem(SESSION);const a=attempts();const exp=sessionStorage.getItem('movida-sst-anemometro-expired')==='1';sessionStorage.removeItem('movida-sst-anemometro-expired');if(exp)msg('Tu sesión de 20 minutos finalizó. Ingresa nuevamente.');else if(a.blockedUntil>Date.now())msg(blocked(a.blockedUntil));$('memberId').focus()}
init();
})();